// provides: MetaPackage
// requires: utf8/utf8.h
// requires: utf8/utf8_charlen.c
// requires: utf8/utf8_character.c
// requires: utf8/utf8_case.c
// requires: utf8/utf8_code.c
// requires: utf8/utf8_width.c
// requires: utf8/utf8_validate.c
// requires: utf8/utf8_encode.c
